/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    orders: Order;
    products: Product;
    brands: Brand;
    categories: Category;
    posts: Post;
    media: Media;
    contacts: Contact;
    newsletter: Newsletter;
    users: User;
    reels: Reel;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    orders: OrdersSelect<false> | OrdersSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    newsletter: NewsletterSelect<false> | NewsletterSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    reels: ReelsSelect<false> | ReelsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  status: 'pending_payment' | 'cod_pending' | 'paid' | 'cancelled' | 'fulfilled';
  guestEmail: string;
  guestFirstName: string;
  guestLastName: string;
  guestPhone: string;
  shippingAddress: string;
  shippingApartment?: string | null;
  shippingCity: string;
  shippingState: string;
  /**
   * ISO country code (e.g. NP, IN).
   */
  shippingCountry: string;
  shippingPostalCode?: string | null;
  paymentMethod: 'cod' | 'pickup' | 'online';
  /**
   * Delivery instructions from the customer.
   */
  orderNotes?: string | null;
  lineItems: {
    product: number | Product;
    productName: string;
    productSku: string;
    unitPrice: number;
    quantity: number;
    lineTotal: number;
    id?: string | null;
  }[];
  subtotal: number;
  discount?: number | null;
  shippingCost?: number | null;
  total: number;
  couponCode?: string | null;
  /**
   * Optional — linked when the customer is signed in.
   */
  user?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * URL-friendly product identifier.
   */
  slug: string;
  status: 'draft' | 'active' | 'archived';
  brand: number | Brand;
  categories: (number | Category)[];
  shortDescription: string;
  /**
   * Original MRP (list price before discount).
   */
  originalPrice?: number | null;
  /**
   * Discount off original price. e.g. 10 = 10% off.
   */
  discountPercentage?: number | null;
  /**
   * Selling price (auto-calculated from original price minus discount).
   */
  price: number;
  /**
   * Auto-set to original price when a discount is applied (shown as strikethrough on storefront).
   */
  compareAtPrice?: number | null;
  sku: string;
  stockQuantity: number;
  isFeatured?: boolean | null;
  /**
   * Show on the Limited Edition catalog page.
   */
  isLimitedEdition?: boolean | null;
  /**
   * Sort order on the Limited Edition page.
   */
  limitedEditionOrder?: number | null;
  /**
   * Homepage showcase buckets (e.g. featured, best-seller, top-seller).
   */
  showcaseSections?: ('featured' | 'best-seller' | 'top-seller' | 'new-arrival')[] | null;
  /**
   * Sort order inside homepage showcase sections.
   */
  showcaseOrder?: number | null;
  featuredImage: number | Media;
  gallery?: (number | Media)[] | null;
  gender?: ('men' | 'women' | 'unisex') | null;
  movement?: ('automatic' | 'quartz' | 'mechanical' | 'smart') | null;
  caseMaterial?: string | null;
  strapMaterial?: string | null;
  dialColor?: string | null;
  caseSizeMm?: number | null;
  waterResistance?: string | null;
  warranty?: string | null;
  specifications?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Comma-separated keywords for search engines.
     */
    keywords?: string | null;
    /**
     * Leave empty to use the default page URL.
     */
    canonicalURL?: string | null;
    robots?: ('index,follow' | 'noindex,nofollow' | 'noindex,follow') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  /**
   * URL-friendly brand identifier,eg:rolex or casio.
   */
  slug: string;
  order_index?: number | null;
  tagline?: string | null;
  description?: string | null;
  /**
   * Main brand hero media for storefront (image or video).
   */
  heroMedia?: (number | null) | Media;
  isActive?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Comma-separated keywords for search engines.
     */
    keywords?: string | null;
    /**
     * Leave empty to use the default page URL.
     */
    canonicalURL?: string | null;
    robots?: ('index,follow' | 'noindex,nofollow' | 'noindex,follow') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  folder: 'brands' | 'products' | 'categories' | 'blog' | 'general';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL-friendly category identifier,eg:luxury-watches.
   */
  slug: string;
  order_index?: number | null;
  tagline?: string | null;
  description?: string | null;
  /**
   * Main category hero media for storefront (image or video).
   */
  heroMedia?: (number | null) | Media;
  isActive?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Comma-separated keywords for search engines.
     */
    keywords?: string | null;
    /**
     * Leave empty to use the default page URL.
     */
    canonicalURL?: string | null;
    robots?: ('index,follow' | 'noindex,nofollow' | 'noindex,follow') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Customers register on the website. Only admins can create staff accounts and assign roles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  phone: string;
  /**
   * Admin: full control. Editor: manage content. Viewer: read-only admin. Customer: website only.
   */
  role: 'admin' | 'editor' | 'viewer' | 'customer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Blog articles for the Sulux Centre storefront.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL-friendly post identifier, e.g. luxury-watch-care-tips.
   */
  slug: string;
  status: 'draft' | 'published' | 'archived';
  /**
   * Short summary shown on blog cards and used as the default SEO description.
   */
  excerpt: string;
  /**
   * Main article content (Lexical rich text).
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Author credited on the post.
   */
  author?: string | null;
  /**
   * Publication date. Auto-set when status changes to Published.
   */
  publishedAt?: string | null;
  /**
   * Estimated reading time in minutes.
   */
  readingTimeMinutes?: number | null;
  /**
   * Total storefront page views for this article.
   */
  viewCount?: number | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Highlight this post on the blog homepage.
   */
  isFeatured?: boolean | null;
  /**
   * Hero image for the post and default social share image.
   */
  featuredImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Comma-separated keywords for search engines.
     */
    keywords?: string | null;
    /**
     * Leave empty to use the default page URL.
     */
    canonicalURL?: string | null;
    robots?: ('index,follow' | 'noindex,nofollow' | 'noindex,follow') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  enquiryType: string;
  brand: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter".
 */
export interface Newsletter {
  id: number;
  email: string;
  status: 'active' | 'unsubscribed';
  source?: ('footer' | 'other') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reels".
 */
export interface Reel {
  id: number;
  platform: 'instagram';
  url: string;
  order?: number | null;
  status?: ('active' | 'inactive') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'contacts';
        value: number | Contact;
      } | null)
    | ({
        relationTo: 'newsletter';
        value: number | Newsletter;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'reels';
        value: number | Reel;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  status?: T;
  guestEmail?: T;
  guestFirstName?: T;
  guestLastName?: T;
  guestPhone?: T;
  shippingAddress?: T;
  shippingApartment?: T;
  shippingCity?: T;
  shippingState?: T;
  shippingCountry?: T;
  shippingPostalCode?: T;
  paymentMethod?: T;
  orderNotes?: T;
  lineItems?:
    | T
    | {
        product?: T;
        productName?: T;
        productSku?: T;
        unitPrice?: T;
        quantity?: T;
        lineTotal?: T;
        id?: T;
      };
  subtotal?: T;
  discount?: T;
  shippingCost?: T;
  total?: T;
  couponCode?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  brand?: T;
  categories?: T;
  shortDescription?: T;
  originalPrice?: T;
  discountPercentage?: T;
  price?: T;
  compareAtPrice?: T;
  sku?: T;
  stockQuantity?: T;
  isFeatured?: T;
  isLimitedEdition?: T;
  limitedEditionOrder?: T;
  showcaseSections?: T;
  showcaseOrder?: T;
  featuredImage?: T;
  gallery?: T;
  gender?: T;
  movement?: T;
  caseMaterial?: T;
  strapMaterial?: T;
  dialColor?: T;
  caseSizeMm?: T;
  waterResistance?: T;
  warranty?: T;
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
        canonicalURL?: T;
        robots?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  order_index?: T;
  tagline?: T;
  description?: T;
  heroMedia?: T;
  isActive?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        canonicalURL?: T;
        robots?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  order_index?: T;
  tagline?: T;
  description?: T;
  heroMedia?: T;
  isActive?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        canonicalURL?: T;
        robots?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  excerpt?: T;
  content?: T;
  author?: T;
  publishedAt?: T;
  readingTimeMinutes?: T;
  viewCount?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  isFeatured?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
        canonicalURL?: T;
        robots?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  enquiryType?: T;
  brand?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter_select".
 */
export interface NewsletterSelect<T extends boolean = true> {
  email?: T;
  status?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reels_select".
 */
export interface ReelsSelect<T extends boolean = true> {
  platform?: T;
  url?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}